theme: jekyll-theme-cayman
title: Minecraft Server
description: A brief description of my project or site.


menu:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Blog
    url: /blog/
  - name: Contact
    url: /contact/
